driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: solaris-11
    driver:
      box: chef/solaris-11
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
  - name: default
    run_list: test::default
  - name: compile_time
    run_list: test::default
    attributes:
      build-essential:
        compile_time: true
